version: '2.3'

services:
  jupyter-notebook:
    image: tf25
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser --allow-root --notebook-dir '/jupyter-home/Jupyter_notebook'
#tail -f /dev/null
    ports:
      - 8888:8888
    restart: always
    volumes:
      - $HOME:/jupyter-home
